const c = {
    NAVPREVIEW:[
        {
            name:"About",
            link:"/about"
        },
        {
            name:"Hero",
            link:"/hero"
        },
        {
            name:"Achievements",
            link:"/achievements"
        },
        {
            name:"Contacts",
            link:"/contacts"
        },
        {
            name:"Education",
            link:"/education"
        },
        {
            name:"Experience",
            link:"/experience"
        },
        {
            name:"Projects",
            link:"/projects"
        },
        {
            name:"Resume",
            link:"/resume"
        },
        {
            name:"Skills",
            link:"/skills"
        },
        {
            name:"Volunteering",
            link:"/volunteering"
        },
    ],
}
export default c;
